services:
  - type: web
    name: elmoder-store
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ELMODER_SECRET_KEY
        generateValue: true
